"""Tests for the ``Session.to_agent_input`` hook (post-merge refactor).

Pins that the prompt preamble is generated by the state subclass — not
by a hardcoded ``f"Incident {id}\\n..."`` shape inside ``runtime.graph``.
The default ``Session`` impl is framework-agnostic; ``IncidentState``
overrides with the incident shape; ``CodeReviewState`` overrides with
PR-shaped text.
"""
from __future__ import annotations

from examples.code_review.state import CodeReviewState, PullRequest
from examples.incident_management.state import IncidentState, Reporter
from runtime.state import Session


def _base_session(**overrides) -> Session:
    fields = dict(
        id="S-1",
        status="in_progress",
        created_at="2026-05-03T00:00:00Z",
        updated_at="2026-05-03T00:00:00Z",
    )
    fields.update(overrides)
    return Session(**fields)


# ---------------------------------------------------------------------------
# Default Session impl — id + status only, plus findings/user_inputs.
# ---------------------------------------------------------------------------


def test_default_session_to_agent_input_is_framework_neutral():
    s = _base_session()
    text = s.to_agent_input()
    assert "Session S-1" in text
    assert "Status: in_progress" in text
    # Must NOT mention domain-specific concepts.
    assert "Incident" not in text
    assert "Environment" not in text
    assert "Pull Request" not in text


def test_default_session_appends_findings_and_user_inputs():
    s = _base_session(
        findings={"triage": "looks like a flake"},
        user_inputs=["operator note: rerun"],
    )
    text = s.to_agent_input()
    assert "Findings (triage): looks like a flake" in text
    assert "operator note: rerun" in text


# ---------------------------------------------------------------------------
# IncidentState override — incident shape (id, env, query, status).
# ---------------------------------------------------------------------------


def test_incident_state_overrides_with_incident_shape():
    inc = IncidentState(
        id="INC-20260503-001",
        status="in_progress",
        created_at="2026-05-03T00:00:00Z",
        updated_at="2026-05-03T00:00:00Z",
        query="api latency",
        environment="production",
        reporter=Reporter(id="alice", team="payments"),
    )
    text = inc.to_agent_input()
    assert "Incident INC-20260503-001" in text
    assert "Environment: production" in text
    assert "Query: api latency" in text
    assert "Status: in_progress" in text


def test_incident_state_includes_findings_and_user_inputs():
    inc = IncidentState(
        id="INC-20260503-002",
        status="in_progress",
        created_at="2026-05-03T00:00:00Z",
        updated_at="2026-05-03T00:00:00Z",
        query="db pool",
        environment="staging",
        reporter=Reporter(id="bob", team="ops"),
        findings={"triage": "pool exhausted"},
        user_inputs=["restart api"],
    )
    text = inc.to_agent_input()
    assert "Findings (triage): pool exhausted" in text
    assert "restart api" in text


# ---------------------------------------------------------------------------
# CodeReviewState override — PR shape (repo, number, title, sha, deltas).
# ---------------------------------------------------------------------------


def test_code_review_state_overrides_with_pr_shape():
    cr = CodeReviewState(
        id="CR-20260503-001",
        status="analyzing",
        created_at="2026-05-03T00:00:00Z",
        updated_at="2026-05-03T00:00:00Z",
        pr=PullRequest(
            repo="acme/api",
            number=42,
            title="harden retry",
            author="alice",
            base_sha="aaa111",
            head_sha="bbb222",
            additions=10,
            deletions=2,
            files_changed=1,
        ),
    )
    text = cr.to_agent_input()
    assert "Pull Request CR-20260503-001" in text
    assert "Repo: acme/api" in text
    assert "PR #42: harden retry" in text
    assert "Author: alice" in text
    # Must NOT leak incident-shaped fields.
    assert "Environment:" not in text
    assert "Query:" not in text
